"""phase 2 projects boq budgets

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_table('cost_codes',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('MATERIAL', 'LABOUR', 'EQUIPMENT', 'SUBCONTRACT', 'TRANSPORT', 'SITE_EXPENSE', 'OVERHEAD', 'CONTINGENCY', 'OTHER', name='costcategory', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code')
    )
    op.create_index(op.f('ix_cost_codes_organization_id'), 'cost_codes', ['organization_id'], unique=False)
    op.create_table('units',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code')
    )
    op.create_index(op.f('ix_units_organization_id'), 'units', ['organization_id'], unique=False)
    op.create_table('unit_conversions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('from_unit_id', sa.Uuid(), nullable=False),
    sa.Column('to_unit_id', sa.Uuid(), nullable=False),
    sa.Column('factor', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['to_unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'from_unit_id', 'to_unit_id')
    )
    op.create_index(op.f('ix_unit_conversions_organization_id'), 'unit_conversions', ['organization_id'], unique=False)
    op.create_table('projects',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'TENDER', 'APPROVED', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CLOSED', name='projectstatus', native_enum=False, length=20), nullable=False),
    sa.Column('contract_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('project_manager_id', sa.Uuid(), nullable=True),
    sa.Column('engineer_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['engineer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code')
    )
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('boqs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', name='approvalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('overhead_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('contingency_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('profit_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boqs_organization_id'), 'boqs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_boqs_project_id'), 'boqs', ['project_id'], unique=False)
    op.create_table('contracts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('contract_no', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('retention_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'contract_no')
    )
    op.create_index(op.f('ix_contracts_organization_id'), 'contracts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contracts_project_id'), 'contracts', ['project_id'], unique=False)
    op.create_table('sites',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sites_project_id'), 'sites', ['project_id'], unique=False)
    op.create_table('boq_items',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('boq_id', sa.Uuid(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('trade', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('unit_id', sa.Uuid(), nullable=False),
    sa.Column('waste_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('material_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('labour_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('equipment_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_code_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['boq_id'], ['boqs.id'], ),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('boq_id', 'item_code')
    )
    op.create_index(op.f('ix_boq_items_boq_id'), 'boq_items', ['boq_id'], unique=False)
    op.create_index(op.f('ix_boq_items_organization_id'), 'boq_items', ['organization_id'], unique=False)
    op.create_table('budgets',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('boq_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', name='approvalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['boq_id'], ['boqs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_budgets_organization_id'), 'budgets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_budgets_project_id'), 'budgets', ['project_id'], unique=False)
    op.create_table('budget_lines',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('budget_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('MATERIAL', 'LABOUR', 'EQUIPMENT', 'SUBCONTRACT', 'TRANSPORT', 'SITE_EXPENSE', 'OVERHEAD', 'CONTINGENCY', 'OTHER', name='costcategory', native_enum=False, length=20), nullable=False),
    sa.Column('cost_code_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('revised_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('committed_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_lines_budget_id'), 'budget_lines', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budget_lines_organization_id'), 'budget_lines', ['organization_id'], unique=False)
    op.create_table('budget_revisions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('budget_id', sa.Uuid(), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('old_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('new_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('revised_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.ForeignKeyConstraint(['line_id'], ['budget_lines.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_revisions_budget_id'), 'budget_revisions', ['budget_id'], unique=False)
    op.create_index(op.f('ix_budget_revisions_organization_id'), 'budget_revisions', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_revisions_organization_id'), table_name='budget_revisions')
    op.drop_index(op.f('ix_budget_revisions_budget_id'), table_name='budget_revisions')
    op.drop_table('budget_revisions')
    op.drop_index(op.f('ix_budget_lines_organization_id'), table_name='budget_lines')
    op.drop_index(op.f('ix_budget_lines_budget_id'), table_name='budget_lines')
    op.drop_table('budget_lines')
    op.drop_index(op.f('ix_budgets_project_id'), table_name='budgets')
    op.drop_index(op.f('ix_budgets_organization_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_boq_items_organization_id'), table_name='boq_items')
    op.drop_index(op.f('ix_boq_items_boq_id'), table_name='boq_items')
    op.drop_table('boq_items')
    op.drop_index(op.f('ix_sites_project_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_contracts_project_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_organization_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_boqs_project_id'), table_name='boqs')
    op.drop_index(op.f('ix_boqs_organization_id'), table_name='boqs')
    op.drop_table('boqs')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_unit_conversions_organization_id'), table_name='unit_conversions')
    op.drop_table('unit_conversions')
    op.drop_index(op.f('ix_units_organization_id'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_cost_codes_organization_id'), table_name='cost_codes')
    op.drop_table('cost_codes')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
