"""phase 3b labour attendance daily logs

Revision ID: 0004
Revises: 0003
"""
from alembic import op
import sqlalchemy as sa


revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('trade', sa.String(length=100), nullable=False),
    sa.Column('contractor', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('overtime_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_code_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code')
    )
    op.create_index(op.f('ix_workers_organization_id'), 'workers', ['organization_id'], unique=False)
    op.create_table('attendance_sheets',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', name='sheetstatus', native_enum=False, length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_comment', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'project_id', 'work_date')
    )
    op.create_index(op.f('ix_attendance_sheets_organization_id'), 'attendance_sheets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_attendance_sheets_project_id'), 'attendance_sheets', ['project_id'], unique=False)
    op.create_table('attendance_entries',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('sheet_id', sa.Uuid(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'LEAVE', name='attendancestatus', native_enum=False, length=20), nullable=False),
    sa.Column('overtime_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cost_code_id', sa.Uuid(), nullable=True),
    sa.Column('days', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('daily_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('overtime_rate', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cost_code_id'], ['cost_codes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['sheet_id'], ['attendance_sheets.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sheet_id', 'worker_id')
    )
    op.create_index(op.f('ix_attendance_entries_organization_id'), 'attendance_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_attendance_entries_sheet_id'), 'attendance_entries', ['sheet_id'], unique=False)
    op.create_index(op.f('ix_attendance_entries_worker_id'), 'attendance_entries', ['worker_id'], unique=False)
    op.create_table('daily_logs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', name='logstatus', native_enum=False, length=20), nullable=False),
    sa.Column('weather', sa.String(length=100), nullable=False),
    sa.Column('work_completed', sa.Text(), nullable=False),
    sa.Column('equipment', sa.Text(), nullable=False),
    sa.Column('issues', sa.Text(), nullable=False),
    sa.Column('safety', sa.Text(), nullable=False),
    sa.Column('quality', sa.Text(), nullable=False),
    sa.Column('tomorrow_plan', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'project_id', 'log_date')
    )
    op.create_index(op.f('ix_daily_logs_organization_id'), 'daily_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_daily_logs_project_id'), 'daily_logs', ['project_id'], unique=False)
    op.create_table('daily_log_progress',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('log_id', sa.Uuid(), nullable=False),
    sa.Column('boq_item_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.String(length=300), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['boq_item_id'], ['boq_items.id'], ),
    sa.ForeignKeyConstraint(['log_id'], ['daily_logs.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_id', 'boq_item_id')
    )
    op.create_index(op.f('ix_daily_log_progress_boq_item_id'), 'daily_log_progress', ['boq_item_id'], unique=False)
    op.create_index(op.f('ix_daily_log_progress_log_id'), 'daily_log_progress', ['log_id'], unique=False)
    op.create_index(op.f('ix_daily_log_progress_organization_id'), 'daily_log_progress', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_log_progress_organization_id'), table_name='daily_log_progress')
    op.drop_index(op.f('ix_daily_log_progress_log_id'), table_name='daily_log_progress')
    op.drop_index(op.f('ix_daily_log_progress_boq_item_id'), table_name='daily_log_progress')
    op.drop_table('daily_log_progress')
    op.drop_index(op.f('ix_daily_logs_project_id'), table_name='daily_logs')
    op.drop_index(op.f('ix_daily_logs_organization_id'), table_name='daily_logs')
    op.drop_table('daily_logs')
    op.drop_index(op.f('ix_attendance_entries_worker_id'), table_name='attendance_entries')
    op.drop_index(op.f('ix_attendance_entries_sheet_id'), table_name='attendance_entries')
    op.drop_index(op.f('ix_attendance_entries_organization_id'), table_name='attendance_entries')
    op.drop_table('attendance_entries')
    op.drop_index(op.f('ix_attendance_sheets_project_id'), table_name='attendance_sheets')
    op.drop_index(op.f('ix_attendance_sheets_organization_id'), table_name='attendance_sheets')
    op.drop_table('attendance_sheets')
    op.drop_index(op.f('ix_workers_organization_id'), table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###
